### ISSUE TITLE
Config and new mechanics

### ISSUE THREAD

**Issue by Kmanqt11** [T2703/Lethal-Company-Heart-Attack#1]
20% way too high, i think it should only happen when your with someone too, for funny factor, and not just randomly dying when no one was there to laugh anyway.

also, what if on fear ur mouse sensitivity drops and ur movement speed drops so it kind of creates the effect of being frozen in fear for a few seconds (like 2.5) ideally small detail: ur movement speed returns to normal slightly earlier, just feels realisitic, dont bother with it tho

also a trembling screen effect would be cool

i love configurable settings but i am a freeloader so idk

**Comment by T2703** [comment]
I can definitely make it so that the heart attack only happens when someone is around. In terms of the new mechanics perhaps I can add in too like it has a chance to happen in terms of of configurable settings I can take a look into it but it will be unlikely as I am working with other projects not sure how the config settings would work with thunderstore.

**Comment by T2703** [comment]
I have implemented the fear mechanic and made tweaks to the heart attack. Now if you're playing multiplayer you must also be with someone in order for it to take effect for the heart attack.
